### ISSUE TITLE
How to build on windows?

### ISSUE THREAD

**Issue by jokoon** [martinRenou/pysfml11#19]
Hello, glad to see you still update this!

Are there some path to specify? Should I use the latest SFML builds or build SFML myself?

I managed to build it with the 2017 64 bits binaries of SFML while adding include and lib directories.

I replaced my old import with those:

` import pysfml11 as sf`

I have this error:

```
Traceback (most recent call last):
  File "C:\eio\_projects\boatery\boatery.py", line 1, in <module>
    import sf_helpers as sfh
  File "C:\eio\_projects\boatery\sf_helpers.py", line 3, in <module>
    import pysfml11 as sf
ImportError: DLL load failed while importing pysfml11: The specified module could not be found.

```

I copied SFML DLL next to python.exe

I now have 

`AttributeError: type object 'pysfml11.Font' has no attribute 'from_file'`

I guess the function name are different from previous versions of python SFML?

Regards :)

**Comment by martinRenou** [comment]
Hey :) Glad you are interested in trying it out!

pysfml11 builds against SFML=2.5, you can find one way to build it here (tested on Windows): https://github.com/martinRenou/pysfml11/blob/master/.github/workflows/main.yml

> I guess the function name are different from previous versions of python SFML?

I guess you are talking about https://github.com/intjelic/python-sfml here? pysfml11 is a different library, which aims at building against the latest SFML and have a simpler codebase. It is not finished yet but I guess you can start using it for simple things. The `Font` has a `load_from_file` method that you can use, this mirrors the `loadFromFile` method in C++.

**Comment by martinRenou** [comment]
I am planning on working on a Python wheel at some point, that way you should be able to do `pip install pysfml11` on Windows and it would work out of the box.

**Comment by jokoon** [comment]
I wonder how difficult it will be to adapt my code to work with pysfml11.

**Comment by jokoon** [comment]
I cannot find Sprite in the graphics test or in the main.cpp file, is that
normal?

**Comment by martinRenou** [comment]
Yes it has not been implemented yet :)

**Comment by jokoon** [comment]
I've tried adding Sprite with

    py::class_<sf::Sprite, sf::Drawable, sf::Transformable>(sfml, "Sprite")
        .def("texture", &sf::Sprite::getTexture, &sf::Sprite::setTexture);

And I'm trying to understand what I did wrong...

**Comment by jokoon** [comment]
Oh there is a boolean in settexture... also texture was not implemented
either...

Jeez that's work ^.^

**Comment by martinRenou** [comment]
Nice! If you could send a PR that would be super super cool!

What's really great about pybind11 is that it makes it easy to make bindings like that, and it won't be difficult to update once a new SFML version comes out.

**Comment by martinRenou** [comment]
The only problem is that it's really repetitive work, not very interesting (hence the pause in development right now ahah). But once the library will be done it won't be hard to maintain.

**Comment by martinRenou** [comment]
Adding the sprite implementation in https://github.com/martinRenou/pysfml11/pull/20

**Comment by martinRenou** [comment]
Closing as answered :)
